version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate JaCoCo Report
          command: mvn jacoco:report

  upload-to-codecov:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - codecov/upload:
          file: target/site/jacoco/jacoco.xml
          token: 3a664fc0-9300-4340-986f-fa33971785a5

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
  upload:
    jobs:
      - upload-to-codecov:
          requires:
            - build
