version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Test
          command: mvn -e test -DskipTests=false
      - run:
          name: Collect coverage
          command: mvn jacoco:report
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
      - run:
          name: Run Checkstyle
          command: mvn checkstyle:check -Dcheckstyle.outputFile=target/checkstyle-result.xml
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            git config --global user.email "ylies.chementel@alumni.univ-avignon.fr"
            git config --global user.name "YliesChementel"

            git clone --branch gh-pages https://github.com/YliesChementel/ceri-m1-techniques-de-test.git gh-pages

            cp -R target/site/apidocs/* gh-pages/

            cd gh-pages
            git add .
            git commit -m "Update Javadoc"
            git push https://YliesChementel:${Javadoc}@github.com/YliesChementel/ceri-m1-techniques-de-test.git gh-pages
orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
