version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Test
          command: mvn test
      - run:
          name: Generate JaCoCo report
          command: mvn jacoco:report
      - codecov/upload

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master