version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Test
          command: mvn test
      - run:
          name: Collect coverage
          command: mvn test -Dmaven.test.failure.ignore=true -Dmaven.coverage.skip=false
      - run:
          name: Upload coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master