version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:21
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master