version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Test
          command: mvn test

  upload-to-codecov:
    docker:
      - image: circleci/openjdk:11
    steps:
      - codecov/upload

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - upload-to-codecov:
          requires:
            - build