version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Test
          command: mvn test

orbs:
  codecov: codecov/codecov@4.0.1

workflows:
  version: 2
  upload-to-codecov:
    jobs:
      - codecov/upload
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master